import { GameAsset } from "@/types/domain";

export const gameAssets: Record<string, GameAsset> = {
  gta_v: {
    gameId: "gta_v",
    backgroundImage: "/images/games/heist-gold-scene.svg",
    heroImage: "/images/games/heist-gold-scene.svg",
    logoImage: "/images/logos/gta-v-logo.svg",
    posterImage: "/images/covers/gta-v.png",
    galleryImages: ["/images/games/heist-gold-scene.svg", "/images/games/liberty-steel-scene.svg"],
    accentColor: "#f2c94c",
    overlayStyle: "glow-grid",
    cardStyle: "glass-gold",
    backgroundPosition: "center center",
    fallbackGradient: "linear-gradient(135deg, #08090a 0%, #17120c 45%, #040404 100%)"
  },
  san_andreas: {
    gameId: "san_andreas",
    backgroundImage: "/images/games/san-andreas-scene.svg",
    heroImage: "/images/games/san-andreas-scene.svg",
    logoImage: "/images/logos/san-andreas-logo.svg",
    posterImage: "/images/covers/san-andreas.jpg",
    galleryImages: ["/images/games/san-andreas-scene.svg"],
    accentColor: "#f0b95f",
    overlayStyle: "dust-bloom",
    cardStyle: "glass-sand",
    backgroundPosition: "center center",
    fallbackGradient: "linear-gradient(135deg, #120907 0%, #2b170e 52%, #090607 100%)"
  },
  vice_city: {
    gameId: "vice_city",
    backgroundImage: "/images/games/vice-neon-scene.svg",
    heroImage: "/images/games/vice-neon-scene.svg",
    logoImage: "/images/logos/vice-city-logo.svg",
    posterImage: "/images/covers/vice-city.jpg",
    galleryImages: ["/images/games/vice-neon-scene.svg", "/images/games/street-racer-scene.svg"],
    accentColor: "#58d5ff",
    overlayStyle: "neon-haze",
    cardStyle: "glass-neon",
    backgroundPosition: "center center",
    fallbackGradient: "linear-gradient(135deg, #070710 0%, #180e2d 45%, #050506 100%)"
  },
  gta_iv: {
    gameId: "gta_iv",
    backgroundImage: "/images/games/liberty-steel-scene.svg",
    heroImage: "/images/games/liberty-steel-scene.svg",
    logoImage: "/images/logos/gta-iv-logo.svg",
    posterImage: "/images/covers/gta-iv.jpg",
    galleryImages: ["/images/games/liberty-steel-scene.svg"],
    accentColor: "#89b6ff",
    overlayStyle: "smoke-steel",
    cardStyle: "glass-steel",
    backgroundPosition: "center center",
    fallbackGradient: "linear-gradient(135deg, #06080e 0%, #141922 45%, #050505 100%)"
  },
  red_dead_redemption: {
    gameId: "red_dead_redemption",
    backgroundImage: "/images/games/frontier-noir-scene.svg",
    heroImage: "/images/games/frontier-noir-scene.svg",
    logoImage: "/images/logos/rdr-logo.svg",
    posterImage: "/images/covers/rdr.jpg",
    galleryImages: ["/images/games/frontier-noir-scene.svg"],
    accentColor: "#e8b36c",
    overlayStyle: "frontier-dust",
    cardStyle: "glass-ember",
    backgroundPosition: "center center",
    fallbackGradient: "linear-gradient(135deg, #130907 0%, #34140f 45%, #060404 100%)"
  },
  red_dead_redemption_2: {
    gameId: "red_dead_redemption_2",
    backgroundImage: "/images/games/frontier-noir-scene.svg",
    heroImage: "/images/games/frontier-noir-scene.svg",
    logoImage: "/images/logos/rdr2-logo.svg",
    posterImage: "/images/covers/rdr2.jpg",
    galleryImages: ["/images/games/frontier-noir-scene.svg", "/images/games/heist-gold-scene.svg"],
    accentColor: "#e8b36c",
    overlayStyle: "frontier-dust",
    cardStyle: "glass-ember",
    backgroundPosition: "center center",
    fallbackGradient: "linear-gradient(135deg, #130907 0%, #2d100b 45%, #050303 100%)"
  },
  la_noire: {
    gameId: "la_noire",
    backgroundImage: "/images/games/noir-detective-scene.svg",
    heroImage: "/images/games/noir-detective-scene.svg",
    logoImage: "/images/logos/la-noire-logo.svg",
    posterImage: "/images/covers/la-noire.jpg",
    galleryImages: ["/images/games/noir-detective-scene.svg"],
    accentColor: "#d0c09a",
    overlayStyle: "film-grain",
    cardStyle: "glass-noir",
    backgroundPosition: "center center",
    fallbackGradient: "linear-gradient(135deg, #040607 0%, #151a20 45%, #040405 100%)"
  },
  bully: {
    gameId: "bully",
    backgroundImage: "/images/games/school-rebel-scene.svg",
    heroImage: "/images/games/school-rebel-scene.svg",
    logoImage: "/images/logos/bully-logo.svg",
    posterImage: "/images/covers/bully.jpg",
    galleryImages: ["/images/games/school-rebel-scene.svg"],
    accentColor: "#ffd55f",
    overlayStyle: "chalk-dust",
    cardStyle: "glass-rebel",
    backgroundPosition: "center center",
    fallbackGradient: "linear-gradient(135deg, #121117 0%, #24161d 45%, #080608 100%)"
  },
  max_payne_3: {
    gameId: "max_payne_3",
    backgroundImage: "/images/games/max-pain-scene.svg",
    heroImage: "/images/games/max-pain-scene.svg",
    logoImage: "/images/logos/max-payne-3-logo.svg",
    posterImage: "/images/covers/max-payne-3.jpg",
    galleryImages: ["/images/games/max-pain-scene.svg"],
    accentColor: "#b3d7ff",
    overlayStyle: "cold-rain",
    cardStyle: "glass-cold",
    backgroundPosition: "center center",
    fallbackGradient: "linear-gradient(135deg, #05070d 0%, #121923 45%, #040405 100%)"
  },
  midnight_club_3: {
    gameId: "midnight_club_3",
    backgroundImage: "/images/games/street-racer-scene.svg",
    heroImage: "/images/games/street-racer-scene.svg",
    logoImage: "/images/logos/midnight-club-3-logo.svg",
    posterImage: "/images/covers/midnight-club-3.jpg",
    galleryImages: ["/images/games/street-racer-scene.svg", "/images/games/vice-neon-scene.svg"],
    accentColor: "#ff7a38",
    overlayStyle: "light-trails",
    cardStyle: "glass-speed",
    backgroundPosition: "center center",
    fallbackGradient: "linear-gradient(135deg, #06070b 0%, #1a1019 45%, #040405 100%)"
  }
};
